WITH CTE AS (
    SELECT REQUESTER_ID as id FROM REQUESTACCEPTED
    UNION ALL
    SELECT ACCEPTER_ID as id FROM REQUESTACCEPTED
)
SELECT id, count(id) as num FROM CTE group by id
ORDER BY num DESC LIMIT 1;